### ISSUE TITLE
The default configuration for shards should use a three member replica set

### ISSUE THREAD

**Issue by jyemin** [mongodb-labs/drivers-evergreen-tools#24]
Currently the shards are configured with a single member replica set.  This was a recent change from using standalones.  But this causes some tests of secondary reads to fail because there is no secondary for mongos to read from.  

So let's use a three member replica set, which is what our users are going to be doing anyway at a minimum.

**Comment by ShaneHarvey** [comment]
Why did you make this change to replica sets: https://github.com/mongodb-labs/drivers-evergreen-tools/commit/d899eb10f7bf8c7385edfdf11aac917fdd6ee92f

Should the shards also have 500 MB oplogs?

**Comment by jyemin** [comment]
Looking back through Java driver test failures on Evergreen I think it had to do with some problems we observed keeping secondaries in sync with an oplog that was too small, but I don't recall for sure any more.  

As the failing test was replica-set only, we can leave shards as is for now.
