### ISSUE TITLE
Add support for Ubuntu 22.04 in download-mongodb.sh script

### ISSUE THREAD

**Issue by autarch** [mongodb-labs/drivers-evergreen-tools#283]
I think we can use the same binaries as 20.04, at least MongoDB v5.0+.

**Comment by autarch** [comment]
Actually, I take it back. Those binaries dynamically link `libnetsnmpmibs.so.30`, which is not installable on Ubuntu 22.04 :(

**Comment by alcaeus** [comment]
Ubuntu 22.04 has been added with #327.
