### ISSUE TITLE
Evergreen platform updates for MongoDB 4.4 (Windows, zSeries)

### ISSUE THREAD

**Issue by ShaneHarvey** [mongodb-labs/drivers-evergreen-tools#91]
Now that MongoDB latest (4.4) requires Windows 10/Windows 2016 (https://jira.mongodb.org/browse/SERVER-45592), MongoDB latest testing is failing on Windows. We should move "latest" testing to Windows 10+ hosts.

We should also remove "latest" zSeries testing.

**Comment by blink1073** [comment]
Closing as out of date
